version: '3'

volumes:
  cache:
    driver: local
  db-data:
    driver: local

services:

  application:
    build:
      context: .
    container_name: book-tracker
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/booktracker_db?currentSchema=booklist
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=sqlpostgre
    ports:
      - '8088:8080' # с локального 8088 будем обращаться к 8080 внутри контейнера

  db:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sqlpostgre
      - POSTGRES_DB=booktracker_db
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass cmZyZWZkMzU0 #base64 password
    volumes:
      - cache:/data