server:
  port: 8088

spring:
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379 #default redis port
      password: cmZyZWZkMzU0
  datasource:
    url: jdbc:postgresql://localhost/booktracker_db?currentSchema=booklist
    username: postgres
    password: sqlpostgre
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
#      data-locations: classpath:demo-data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: booklist

security:
  jwt:
    secret: ZWZqb3B3ZWpmd2plY2Zwd2plY2Zwb2p3ZWNmb2x3ZWNmcG93 #while secret is not change - all users keys stay valid
    access: 3600000 #1 hour
    refresh: 2592000000 #30 days

springdoc:
  override-with-generic-response: false

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml